{"uuid": "be0e3fbb-3685-4876-8524-2ff9f8aa5c70", "children": ["8e8fe8e3-e36c-46de-8d50-6b538d1b9863"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "AttributeError: 'Android_UI_Client' object has no attribute 'driver'\n", "trace": "  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\cases\\app_ui\\android\\test_login.py\", line 19, in setup\n    self.lg = LoginPage(app.driver, app.appium_hub)\n                        ^^^^^^^^^^\n"}, "start": 1757575929461, "stop": 1757575930777}], "start": 1757575929461, "stop": 1757575930783}