{"uuid": "7ebb8771-dbf4-49f3-a7b3-ef50f683700f", "children": ["e60a637e-2d1b-443c-9a00-f44018ae5d66"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "AttributeError: 'Android_UI_Client' object has no attribute 'driver'\n", "trace": "  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\cases\\app_ui\\android\\test_login.py\", line 19, in setup\n    self.lg = LoginPage(app.driver, app.appium_hub)\n                        ^^^^^^^^^^\n"}, "start": 1757575925494, "stop": 1757575926810}], "start": 1757575925494, "stop": 1757575926817}