{"uuid": "264b1b82-7111-47b1-b04b-036b4fc95a89", "children": ["3ba9dcb9-7b57-416c-95eb-d1963df5ed5b", "7af7e8cb-6c04-4d58-997b-b4d2f75d6ab4", "1661fd95-1e84-4e0f-bcbd-a85dff488f8e", "8c4e6c84-eb31-4f2f-b5e7-f72999846bb1", "d1859bc6-d5b1-4e19-aebf-ef70725675f7", "3073ff5e-659b-4467-be57-b8dc8035b922", "e4b4752a-2e79-4f4f-88f2-a1daab422fdf", "e3d78503-9b6f-40d2-8611-c8fcef32c3ff"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "KeyError: 'server_url'\n", "trace": "  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\cases\\app_ui\\android\\conftest.py\", line 8, in app\n    driver = Android_UI_Client()\n             ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\base\\android\\android_ui_client.py\", line 33, in __init__\n    self.device_info[\"server_url\"]\n    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n"}, "start": 1757580554443, "stop": 1757580554443}], "start": 1757580554443, "stop": 1757580554510}